### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by ElgarL** [Hachifac/idolBot#8]
Locations for the Options button have changed as of 16th August 2018.

**Comment by Hachifac** [comment]
Thanks, fixed in 1.5.2!

**Comment by TheAndy7** [comment]
After lastest update, the bot misses (by just a hair) the reset button.

**Comment by TheAndy7** [comment]
Looks like the reset location issue is due to, "This problem is due to a new line with a bonus + 150% idols on event mission."
