### ISSUE TITLE
[Bug] Bot gets stuck looking for the cog to recognize it's out of the chests window

### ISSUE THREAD

**Issue by RedSnt** [Hachifac/idolBot#9]
I posted about this [on Reddit some days ago](https://www.reddit.com/r/cotlibot/comments/98hn01/idolbot_152/e4gdq99/), but only just now looked into the code a bit, and I found that the bot gets stuck with this message in console: "Still in the chests window" which is a check that is done in the botMainLoop.ahk file. 
The error occurs on line 389 where it, from my understanding anyway, is looking for the cog but that has since changed location and it therefore gets stuck. 
In botInternalFunctions on line 547 it looks like, in the log as well, that the bot is able to find the cog. 
But I haven't had any luck using the same coordinates on line 389 in botMainLoop to correctly make the chest opening sequence to work, it still stalls at "Still in the chests window."

I tried to widen the search area of the ImageSearch function, but that doesn't work either.
So yeah, not sure why it isn't working, I'm not really a programmer - all I know is that it from the error message in the log, the error should be the cog finding function on line 389 in botMainLoop.ahk.

**Comment by RedSnt** [comment]
Ugh.. So I'm a dum dum and the fix does work, I was running the compiled version again and again. But now that I run the idolBot.ahk aka the uncompiled version it correctly use the changes in botMainLoop.ahk and now it correctly resets after using chests!

So the fix is simple enough: Instead of using on line 389 in botMainLoop.ahk:
`ImageSearch, OutputX, OutputY, 298, 90, 340, 130, *150 images/game/cog.png`
replace it with
`ImageSearch, OutputX, OutputY, 15, 95, 40, 125, *150 images/game/cog.png`

It's basically your own fix as it's a copy/paste from botInternalFunctions line 547 😋

**Comment by Hachifac** [comment]
It'll be added in the next version, thanks! :)
